### PR TITLE
improved fragment shader

### PR DESCRIPTION
**Pull request by jereremy**
changed the castray function in the fragment shader that fixes the weird graphical errors

### CODE REVIEW

**Comment by jereremy** [comment]
I completely missed the depth optimization you did. I implemented my own SDF based version of the optimization where you can manually set the max skip step amount with SDF_RADIUS in render.cpp and the SDF automatically updates when you destroy and place voxels. The generation of the SDF is quite slow when you get past a skip radius of 10, a good idea would be to multithread it or somehow put it in a compute shader.

**Comment by Berry2460** [comment]
Hi, thank you for the input! I like the idea of encoding a float within the depth field data instead of an integer, that seems to solve the issue. Unfortunately though, for the rest I don't think I can commit this for future merge conflicts and consistency. I have been slowly working on this project locally with multi-threading, and coincidentally revamping the fragment shader using a similar research paper for reference.

**Comment by jeremymetzler** [comment]
interested in seeing your progress

**Comment by jereremy** [comment]
You're welcome! I also have been working on this locally and have
implemented my own GI raytracing (not even close to physically accurate)
and multipass denoising. Looking forward to see your progress.

**Comment by jeremymetzler** [comment]
[image: image.png]

**Pull request closed without merging**
